<header id="header" class="header d-flex align-items-center justify-content-end">
    <a href="leisure_areas" class="btn btn-dark text-white ml-auto mr-1" title="Consultar eventos agendados">
        <i class="fa fa-calendar" aria-hidden="true"></i>
    </a>
    <button class="btn btn-light btn-user border-0 mr-3" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="text-dark">
            Olá,
        </span>
        <span class="text-secondary mr-1">
            <?= $_SESSION['nome'] ?>
        </span>
        <img width="35" height="35" src="img/users/<?= $_SESSION['imagem_usuario'] ?>">
    </button>
    <div class="dropdown-menu drop" aria-labelledby="dropdownMenuButton">
        <a href="/my_profile">
            <i class="fas fa-user-alt"></i>
            <span class="ml-2">
                Meu Perfil
            </span>
        </a>
        <hr class="m-0">
        <a href="#" data-toggle="modal" data-target="#apartamento-modal">
        <i class="fa fa-building" aria-hidden="true"></i>
            <span class="ml-2">
                Apartamento(s)
            </span>
        </a>
        <hr class="m-0">
        <a href="/sign_out">
            <i class="fas fa-sign-out-alt"></i>
            <span class="ml-2">
                Sair
            </span>
        </a>
    </div>
</header>
<div class="container-fluid">
    <div class="row dashboard-gradient">
        <!-- <a href="/visitors" class="col-md-6 bg-1 text-center">
            <h1 class="text-white"><i class="fas fa-walking px-2"></i>Visitantes</h1>
        </a> -->
        <a href="/cars" class="col-md-6 bg-1 text-center">
            <h1 class="text-white"><i class="fas fa-car px-2"></i>Veículo(s)</h1>
        </a>
        
        <a href="/residents" class="col-md-6 bg-4 text-center">
            <h1 class="text-white"><i class="fas fa-building px-2"></i>Moradores</h1>
        </a>
        <!-- <a href="/service_providers" class="col-md-6 bg-2 text-center">
            <h1 class="text-white"><i class="fas fa-toolbox px-2"></i>Prestadores de serviços</h1>
        </a> -->
        

    </div>
    <div class="row dashboard-gradient">
        <a href="/orders" class="col-md-6 bg-3 text-center">
            <h1 class="text-white"><i class="fas fa-dolly px-2"></i>Encomendas</h1>
        </a>

        <a href="/leisure_areas" class="col-md-6 bg-2 text-center">
            <h1 class="text-white"><i class="fas fa-gamepad px-2"></i>Evento(s)</h1>
        </a>
    </div>
    
    <!-- <div class="row dashboard-gradient">
        <a href="/leisure_areas" class="col-md-6 bg-1 text-center">
            <h1 class="text-white"><i class="fas fa-gamepad px-2"></i>Evento(s)</h1>
        </a>
    </div> -->
</div>

<!-- Modal de apartamento -->
<div class="modal fade" id="apartamento-modal" tabindex="-1" role="dialog" aria-labelledby="title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content border-0">
            <div class="modal-header text-center align-items-center">
                <h4 class="modal-title font-weight-bold text-secondary">Apartamento(s)</h4>
                <button type="button" class="close border-0" data-dismiss="modal" aria-label="Close">  
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="seleciona_apartamento" method="post">
                <div class="modal-body py-4">
                    <div class="card card-body border-0 pt-0">
                        <label class="mt-4 mb-0 text-secondary">Apartamento</label>
                        <select name="id_apartamento" id="id_apartamento" class="form-custom form-control m-0 p-0" style="border-bottom: 2px solid #20B2AA!important;" required>
                            <option value="" disabled selected>Selecione o Apartamento</option>
                            <?php foreach ($_SESSION['apartamentos'] as $e) { ?>
                                <option value="<?= $e['id_apartamento'] ?>" <?php if($_SESSION['apartamento']['id_apartamento'] == $e['id_apartamento']){echo 'selected';}?>><?= $e['dsc_apartamento'] ?></option>
                            <?php } ?>
                        </select>
                        <!-- <br>
                        <br>
                        <div class="invalid-feedback" id="cad-invalid"></div> -->
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" id="registrar" class="btn w-100 text-light">Aplicar</button>
                    <!-- <button type="submit" id="validar" class="btn w-100 text-light">Aplicar</button> -->
                </div>
            </form>
        </div>
    </div>
</div>