<header id="" class="header d-flex align-items-center justify-content-between position-fixed">
    <div class="button ml-3 text-center" onclick="sidebarUser()">
        <i class="fas fa-bars"></i>
    </div>
    <!-- <a href="leisure_areas" class="btn btn-dark text-white ml-auto mr-1" title="Consultar eventos agendados">
        <i class="fa fa-calendar" aria-hidden="true"></i>
    </a> -->
    <button class="btn btn-light btn-user border-0 mr-3" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="text-dark">
            Olá,
        </span>
        <span class="text-secondary mr-1">
            <?= $_SESSION['nome'] ?>
        </span>
        <img width="35" height="35" src="img/users/<?= $_SESSION['imagem_usuario'] ?>">
    </button>
    <div class="dropdown-menu drop" aria-labelledby="dropdownMenuButton">
        <a href="/my_profile">
            <i class="fas fa-user-alt"></i>
            <span class="ml-2">
                Meu Perfil
            </span>
        </a>
        <hr class="m-0">
        <a href="/sign_out">
            <i class="fas fa-sign-out-alt"></i>
            <span class="ml-2">
                Sair
            </span>
        </a>
    </div>
</header>
<div class="container-fluid dashboard-gradient menu-user mt-10vh" id="menu-user" style="margin-left: -100%;">
    <div class="row dashboard-gradient">
        <a href="/visitors" class="col-md-6 bg-1 text-center">
            <h1 class="text-white"><i class="fas fa-walking px-2"></i>Visitantes</h1>
        </a>
        <a href="/service_providers" class="col-md-6 bg-2 text-center">
            <h1 class="text-white"><i class="fas fa-toolbox px-2"></i>Prestadores de serviços</h1>
        </a>
    </div>
    <div class="row dashboard-gradient">
        <a href="/orders" class="col-md-6 bg-3 text-center">
            <h1 class="text-white"><i class="fas fa-dolly px-2"></i>Encomendas</h1>
        </a>
        <a href="/residents" class="col-md-6 bg-4 text-center">
            <h1 class="text-white"><i class="fas fa-building px-2"></i>Moradores</h1>
        </a>
    </div>
</div>
<section class="container-fluid ontent-user p-3">
    <div class="table-events ">
        <ol class="breadcrumb mb-4 bg-dark justify-content-between">
            <li class="breadcrumb-item active text-light">
                <h4 class="m-0"><i class="fa fa-calendar mr-3 ml-2" style="font-size:28px"></i>Eventos agendados</h4>
            </li>
        </ol>
    </div>
    <div class="card mb-4 border-0 shadow p-4">
        <table class=" table-bordered table-hover mb-0 display responsive nowrap" style="width:100%" id="dataTableCad" role="tabpanel" aria-labelledby="dataTable-tab">
            <thead class="text-center card-header text-dark">
                <tr>
                    <th>Local</th>
                    <th>Inicio do evento</th>
                    <th>Fim do evento</th>
                </tr>
            </thead>
            <tbody class="text-center">
                <?php foreach ($this->view->event as $e) { ?>
                    <tr>
                        <td><?= $e['titulo_evento'] ?></td>
                        <td><?= date('d/m/Y H:i', strtotime($e['inicio_evento'])) ?></td>
                        <td><?= date('d/m/Y H:i', strtotime($e['fim_evento'])) ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</section>

<section class="card mb-4 p-4" id="content">
    <div id="calendar" class="calendar shadow"></div>
</section>

<!-- Modal de cadastro-->
<div class="modal fade" id="cadastrar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content border-0">
            <div class="modal-header text-center align-items-center">
                <h4 class="modal-title font-weight-bold text-secondary">Agendar evento</h4>
                <button type="button" class="close border-0" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="/register_event" method="post" id="addevent" enctype="multipart/form-data">
                <div class="modal-body py-4">
                    <div class="card card-body border-0 pt-0">
                        <div class="label-float">
                            <input type="text" name="cpf" class="form-custom form-control mt-2" size="60" maxlength="14" id="cpf"  placeholder="CPF" required>
                            <label>CPF</label>
                            <div class="invalid-feedback" id="invalid">
                                CPF inválido!
                            </div>
                        </div>
                        <label class="mt-4 mb-0 text-secondary">Local</label>
                        <select class="form-custom form-control m-0 p-0" name="titulo_evento" style="border-bottom: 2px solid #20B2AA!important;">
                            <option value="Salão de festas">Salão de festas</option>
                            <option value="Churrasqueira">Churrasqueira</option>
                        </select>
                        <div class="label-float mt-4">
                            <input type="datetime-local" onkeyup="validaDataAntiga();" onkeydown="validaDataAntiga();" onchange="validaDataAntiga();" name="inicio_evento" class="form-custom form-control mt-2" size="60" id="inicio_evento" onkeypress="DataHora(event, this)" placeholder="Início do evento" required>
                            <label>Início do evento</label>
                        </div>
                        <div class="label-float mt-4">
                            <input type="datetime-local" name="fim_evento" onkeyup="somaDataLimite();" onkeydown="somaDataLimite();" onchange="somaDataLimite();" class="form-custom form-control mt-2" size="60" id="fim_evento" onchange="somaData();" onkeypress="DataHora(event, this)" placeholder="Fim do evento" required>
                            <label>Fim do evento</label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-register w-100 text-light" onclick="return valida()">Cadastrar</button>
                </div>
            </form>
        </div>
    </div>
</div>


<script src='lib/fullcalendar/core/main.min.js'></script>
<script src='lib/fullcalendar/core/locales/pt-br.js'></script>
<script src='lib/fullcalendar/daygrid/main.min.js'></script>
<script src='lib/fullcalendar/interaction/main.min.js'></script>
<script src='lib/fullcalendar/list/main.min.js'></script>
<script src='lib/fullcalendar/timegrid/main.min.js'></script>
<script src="js/calendar.js"></script>
<script>
    function validaDataAntiga(){
        if(new Date($('#inicio_evento').val()) < new Date){
            alert("A data/hora escolhida não pode ser anterior a data/hora atual!");
            $('#inicio_evento').val('');
        } 
    }

    function somaData(){
    const dataLimite = new Date($('#fim_evento').val());
    const dataAtual = new Date();
       if(dataLimite > (new Date(dataAtual.setDate(dataAtual.getDate() + 90)))){
           alert("A data/hora escolhida não pode ser maior do que a data atual + 90 dias!");
           $('#fim_evento').val('');
       } 
    }

    function somaDataLimite(){
    const dataLimite = new Date($('#fim_evento').val());
    const dataAtual = new Date($('#inicio_evento').val());
       if(dataLimite.toDateString() > (new Date(dataAtual.setDate(dataAtual.getDate()))).toDateString()){
           alert("A data/hora fim escolhida não pode ser maior do que a data de inicio do evento!");
           $('#fim_evento').val('');
       } 
    }
    
</script>