<header id="" class="header d-flex align-items-center justify-content-between position-fixed">
    <div class="button ml-3 text-center" onclick="sidebarUser()">
        <i class="fas fa-bars"></i>
    </div>
    <!-- <a href="leisure_areas" class="btn btn-dark text-white ml-auto mr-1" title="Consultar eventos agendados">
        <i class="fa fa-calendar" aria-hidden="true"></i>
    </a> -->
    <button class="btn btn-light btn-user border-0 mr-3" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="text-dark">
            Olá,
        </span>
        <span class="text-secondary mr-1">
            <?= $_SESSION['nome'] ?>
        </span>
        <img width="35" height="35" src="img/users/<?= $_SESSION['imagem_usuario'] ?>">
    </button>
    <div class="dropdown-menu drop" aria-labelledby="dropdownMenuButton">
        <a href="/my_profile">
            <i class="fas fa-user-alt"></i>
            <span class="ml-2">
                Meu Perfil
            </span>
        </a>
        <?php if(($_SESSION['nivel_acesso'] !== 'administrador') && ($_SESSION['nivel_acesso'] !== 'porteiro')){?>
        <hr class="m-0">
        <a href="#" data-toggle="modal" data-target="#apartamento-modal">
        <i class="fa fa-building" aria-hidden="true"></i>
            <span class="ml-2">
                Apartamento(s)
            </span>
        </a>
        <?php } ?>
        <hr class="m-0">
        <a href="/sign_out">
            <i class="fas fa-sign-out-alt"></i>
            <span class="ml-2">
                Sair
            </span>
        </a>
    </div>
</header>
<div class="container-fluid dashboard-gradient menu-user" id="menu-user" style="margin-left: -100%;">
    <div class="row dashboard-gradient">
        <a href="/visitors" class="col-md-6 bg-1 text-center">
            <h1 class="text-white"><i class="fas fa-walking px-2"></i>Visitantes</h1>
        </a>
        <a href="/service_providers" class="col-md-6 bg-2 text-center">
            <h1 class="text-white"><i class="fas fa-toolbox px-2"></i>Prestadores de serviços</h1>
        </a>
    </div>
    <div class="row dashboard-gradient">
        <a href="/orders" class="col-md-6 bg-3 text-center">
            <h1 class="text-white"><i class="fas fa-dolly px-2"></i>Encomendas</h1>
        </a>
        <a href="/residents" class="col-md-6 bg-4 text-center">
            <h1 class="text-white"><i class="fas fa-building px-2"></i>Moradores</h1>
        </a>
    </div>
</div>
<section class="content-user p-3" id="">
    <ol class="breadcrumb mb-4 bg-dark justify-content-between">
        <li class="breadcrumb-item active">
            <button class="btn btn-outline-light" data-toggle="modal" data-target="#cad-modal"
            <?php 
                if($this->view->cont_veiculos >= $this->view->cont_vagas){
                    //echo "disabled";
                }
            ?>
            >
                <h4 class="m-0 d-sm-block d-none"><i class="fas fa-car mr-3 ml-2" style="font-size:28px"></i>Cadastar Veículo</h4>
                <h4 class="m-0 d-sm-none d-block"><i class="fas fa-walking mr-3 ml-2" style="font-size:28px"></i>Cadastar</h4>
            </button>
        </li>
        <!-- <button class="btn bg-transparent btn-exports px-3" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-ellipsis-v text-white"></i>
        </button> -->
        <div class="dropdown-menu drop p-0" aria-labelledby="dropdownMenuButton">
            <h6 class="p-2">Exportar</h6>
            <a type="button" data-toggle="modal" data-target="#export-modal">
                <i class="far fa-file-excel"></i>
                <span class="ml-1">Para Excel</span>
            </a>
        </div>
    </ol>
    <div class="card mb-4 border-0 shadow">
        <!-- <div class="row justify-content-between add-exit">
            <div class="card-header text-center add col-md-6" data-toggle="modal" data-target="#form-modal">
                <h5 class="m-0"><i class="fas fa-door-open text-white mr-1"></i>Registrar Entrada</h5>
            </div>
            <div class="card-header text-center exit col-md-6" data-toggle="modal" data-target="#view-modal">
                <h5 class="m-0">
                    <i class="fas fa-door-open text-white mr-1"></i>
                    Registrar Saída
                    <?php if ($this->view->total_visitantes_presentes) { ?>
                        <span class="badge badge-pill badge-danger" title="Total de visitantes presentes no condomínio"><?= $this->view->total_visitantes_presentes ?></span>
                    <?php } ?>
                </h5>
            </div>
        </div> -->
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item col" role="presentation">
                <a class="nav-link tabelas active" id="registros-tab" data-toggle="tab" href="#registros" role="tab" aria-controls="registros" aria-selected="true">
                    Registros <span class="d-sm-inline-block d-none">de entrada</span>
                </a>
            </li>
            <!-- <li class="nav-item col" role="presentation">
                <a class="nav-link tabelas" id="cadastros-tab" data-toggle="tab" href="#cadastros" role="tab" aria-controls="cadastros" aria-selected="false">
                    <span class="d-sm-inline-block d-none">Visitantes cadastrados</span>
                    <span class="d-sm-none d-inline-block">Cadastros</span>
                </a>
            </li> -->
        </ul>

        <div class="card-body table-responsive pt-1 ">
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="registros" role="tabpanel" aria-labelledby="registros-tab">
                    <table class="table-bordered table-hover mb-0 display responsive nowrap" style="width:100%" id="dataTable" role="tabpanel" aria-labelledby="dataTable-tab">
                        <thead class="text-center card-header text-dark">
                            <tr>
                                <th>Veículo</th>
                                <th>Cor</th>
                                <th>Placa</th>
                                <th>Vaga</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody class="text-center">
                            <?php foreach ($this->view->registros_entrada as $e) { ?>
                                <tr>
                                    <td><?= $e['dsc_veiculo'] ?></td>
                                    <td style="background-color: <?= $e['cor_veiculo'] ?>;"></td>
                                    <td><?= $e['placa_veiculo'] ?></td>
                                    <td><?= $e['dsc_vaga_garagem'] ?></td>
                                    <td>
                                    <form action="/delete_car" method="post">
                                        <input type="hidden" name="id_veiculo" value="<?= $e['id_veiculo'] ?>">
                                        <button type="submit" class="btn btn-info" style="width:120px"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                    </form>
                                    </td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
                
            </div>
        </div>
    </div>
</section>

<!-- Modal de cadastro -->
<div class="modal fade" id="cad-modal" tabindex="-1" role="dialog" aria-labelledby="title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content border-0">
            <div class="modal-header text-center align-items-center">
                <h4 class="modal-title font-weight-bold text-secondary">Cadastrar Veículo</h4>
                <button type="button" class="close border-0" data-dismiss="modal" aria-label="Close">  
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="register_car" method="post">
                <div class="modal-body py-4">
                    <div class="card card-body border-0 pt-0">
                        <div class="label-float">
                            <input type="text" name="dsc_veiculo" id="dsc_veiculo" class="form-custom form-control mt-2" size="60" placeholder="Nome Veículo" maxlength="60" required onkeyup="validarDsc(this)" autofocus>
                            <label>Nome/Marca do Veículo</label>
                        </div>
                        <br>
                        <label id="label-placa_veiculo" class="mt-4 mb-0 text-secondary">Cor do Veículo</label>
                        <input type="color" id="cor_veiculo" name="cor_veiculo" value="#c0c0c0" required>
                        <br>
                        <br>
                        <div class="label-float">
                        <input type="text" id="placa_veiculo" name="placa_veiculo" class="form-custom form-control mt-2" size="60" onkeyup="validarPlaca(this)" placeholder="ABC-1234" maxlength="8" autofocus required>
                            <label>Placa</label>
                        </div>
                        <label class="mt-4 mb-0 text-secondary">Vaga</label>
                        <select name="id_vaga_garagem" id="id_vaga_garagem" class="form-custom form-control m-0 p-0" style="border-bottom: 2px solid #20B2AA!important;" required>
                            <option value="" disabled selected>Selecione a Vaga</option>
                            <?php foreach ($this->view->vagas_garagemDisponivel as $e) { ?>
                                <option value="<?= $e['id_vaga_garagem'] ?>"><?= $e['dsc_vaga_garagem'] ?></option>
                            <?php } ?>
                        </select>
                        <br>
                        <br>
                        <div class="invalid-feedback" id="cad-invalid"></div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" id="registrar" class="btn w-100 text-light" onclick="return validaCadastroCars()">Cadastrar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal de registro de entrada-->
<div class="modal fade" id="form-modal" tabindex="-1" role="dialog" aria-labelledby="title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content border-0">
            <div class="modal-header text-center align-items-center">
                <h4 class="modal-title font-weight-bold text-secondary">Registrar Entrada</h4>
                <button type="button" class="close border-0" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="register_entry_visitor" method="post">
                <div class="modal-body py-4">
                    <div class="card card-body border-0 pt-0">
                        <label class="mt-0 mb-0 text-secondary">Documento</label>
                        <select id="select-documento-registro" name="documento" class="form-custom form-control m-0 p-0" style="border-bottom: 2px solid #20B2AA!important;">
                            <option value="CPF">CPF</option>
                            <option value="RG">RG</option>
                        </select>
                        <div class="label-float mt-4" id="input-cpf-registro">
                            <input type="text" id="cpf" name="cpf" class="form-custom form-control mt-2" size="60" placeholder="CPF" maxlength="14">
                            <label>CPF</label>
                            <div class="invalid-feedback" id="invalid">
                                CPF inválido!
                            </div>
                        </div>
                        <label id="label-uf-registro" class="mt-4 mb-0 text-secondary">UF</label>
                        <select id="select-uf-registro" name="uf" class="form-custom form-control m-0 p-0" style="border-bottom: 2px solid #20B2AA!important;">
                            <option value="SP">SP</option>
                            <option value="AC">AC</option>
                            <option value="AL">AL</option>
                            <option value="AM">AM</option>
                            <option value="AP">AP</option>
                            <option value="BA">BA</option>
                            <option value="CE">CE</option>
                            <option value="DF">DF</option>
                            <option value="ES">ES</option>
                            <option value="GO">GO</option>
                            <option value="MA">MA</option>
                            <option value="MG">MG</option>
                            <option value="MS">MS</option>
                            <option value="MT">MT</option>
                            <option value="PA">PA</option>
                            <option value="PB">PB</option>
                            <option value="PI">PI</option>
                            <option value="PE">PE</option>
                            <option value="PR">PR</option>
                            <option value="RJ">RJ</option>
                            <option value="RN">RN</option>
                            <option value="RO">RO</option>
                            <option value="RR">RR</option>
                            <option value="RS">RS</option>
                            <option value="SC">SC</option>
                            <option value="SE">SE</option>
                            <option value="TO">TO</option>
                        </select>
                        <div class="label-float mt-4" id="input-rg-registro">
                            <input type="text" id="rg" name="rg" class="form-custom form-control mt-2" maxlength="14" size="60" placeholder="RG">
                            <label>RG</label>
                        </div>
                        <div class="label-float mt-4">
                            <input type="text" name="apartamento" class="form-custom form-control mt-2" size="60" placeholder="Apartamento" maxlength="5" required>
                            <label>Apartamento</label>
                        </div>
                        <label class="mt-4 mb-0 text-secondary">Bloco</label>
                        <select class="form-custom form-control m-0 p-0" name="bloco" style="border-bottom: 2px solid #20B2AA!important;">
                            <option value="A">A</option>
                            <option value="B">B</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-register w-100 text-light" onclick="return valida()">Registrar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal de visualização-->
<div class="modal fade" id="view-modal" tabindex="-1" role="dialog" aria-labelledby="title" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered">
        <div class="modal-content border-0">
            <div class="modal-header text-center align-items-center">
                <h4 class="modal-title font-weight-bold text-secondary">Registrar Saída</h4>
                <button type="button" class="close border-0" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="card-body table-responsive pt-1">
                <table class="display responsive nowrap table-bordered table-hover mb-0" id="dataTableModal" style="width: 100%;">
                    <thead class="text-center card-header text-dark">
                        <tr>
                            <th>Nome</th>
                            <th>CPF / RG</th>
                            <th>UF</th>
                            <th>Apartamento</th>
                            <th>Bloco</th>
                            <th>Entrada</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        <?php foreach ($this->view->visitantes_presentes as $e) { ?>
                            <tr>
                                <td><?= $e['nome'] ?></td>
                                <td><?= $e['cpf_rg'] ?></td>
                                <td><?= $e['uf'] ?></td>
                                <td><?= $e['apartamento'] ?></td>
                                <td><?= $e['bloco'] ?></td>
                                <td><?= date('d/m/Y H:i', strtotime($e['data_entrada'])) ?></td>
                                <th>
                                    <form action="/register_exit_visitor" method="post" class="d-inline-block">
                                        <input type="hidden" name="id_visitante" value="<?= $e['id_visitante'] ?>">
                                        <abbr title="Registrar saída">
                                            <button type="submit" class="btn btn-warning btn-action text-white w-100">
                                                <i class="fas fa-door-open"></i>
                                                Registrar Saída
                                            </button>
                                        </abbr>
                                    </form>
                                </th>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Modal de exportação-->
<div class="modal fade" id="export-modal" tabindex="-1" role="dialog" aria-labelledby="title" aria-hidden="true">
    <div class="modal-dialog modal-md modal-dialog-centered">
        <div class="modal-content border-0">
            <div class="modal-header text-center align-items-center">
                <h4 class="modal-title font-weight-bold text-secondary">Exportação de dados</h4>
                <button type="button" class="close border-0" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="/export_visitors" method="post">
                <div class="modal-body py-4">
                    <div class="card card-body border-0 pt-0">
                        <label class="mt-2 mb-0 text-secondary">Categoria</label>
                        <select id="select-documento-export" name="categoria" class="p-0 form-custom form-control m-0 p-0" style="border-bottom: 2px solid #20B2AA!important;">
                            <option value="Cadastros">Visitantes cadastrados</option>
                            <option value="Registros">Registros de entrada</option>
                        </select>

                        <label id="label-periodo-export" class="mt-4 mb-0 text-secondary">Período</label>
                        <select id="select-periodo-export" name="periodo" class="form-custom form-control m-0 p-0" style="border-bottom: 2px solid #20B2AA!important;">
                            <option value="Todo o período">Todo o período</option>
                            <option value="Personalizado">Personalizado</option>
                        </select>

                        <div class="d-flex align-items-center justify-content-between">
                            <div id="label-data-inicio" class="label-float mt-4 mr-2">
                                <input type="date" id="input-data-inicio" name="data-inicio" class="form-custom form-control mt-2" maxlength="10" size="60" placeholder="Data inicial">
                                <label>Data inicial</label>
                            </div>
                            <div id="label-data-fim" class="label-float mt-4 ml-2">
                                <input type="date" id="input-data-fim" name="data-fim" class="form-custom form-control mt-2" maxlength="10" size="60" placeholder="Data final">
                                <label>Data final</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-register text-white w-100">Exportar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal de apartamento -->
<div class="modal fade" id="apartamento-modal" tabindex="-1" role="dialog" aria-labelledby="title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content border-0">
            <div class="modal-header text-center align-items-center">
                <h4 class="modal-title font-weight-bold text-secondary">Apartamento(s4)</h4>
                <button type="button" class="close border-0" data-dismiss="modal" aria-label="Close">  
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="seleciona_apartamento" method="post">
                <div class="modal-body py-4">
                    <div class="card card-body border-0 pt-0">
                        <label class="mt-4 mb-0 text-secondary">Apartamento</label>
                        <select name="id_apartamento" id="id_apartamento" class="form-custom form-control m-0 p-0" style="border-bottom: 2px solid #20B2AA!important;" required>
                            <option value="" disabled selected>Selecione o Apartamento</option>
                            <?php foreach ($_SESSION['apartamentos'] as $e) { ?>
                                <option value="<?= $e['id_apartamento'] ?>" <?php if($_SESSION['apartamento']['id_apartamento'] == $e['id_apartamento']){echo 'selected';}?>><?= $e['dsc_apartamento'] ?></option>
                            <?php } ?>
                        </select>
                        <!-- <br>
                        <br>
                        <div class="invalid-feedback" id="cad-invalid"></div> -->
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" id="registrar" class="btn w-100 text-light">Aplicar</button>
                    <!-- <button type="submit" id="validar" class="btn w-100 text-light">Aplicar</button> -->
                </div>
            </form>
        </div>
    </div>
</div>



<script src='lib/fullcalendar/core/main.min.js'></script>
<script src='lib/fullcalendar/core/locales/pt-br.js'></script>
<script src='lib/fullcalendar/daygrid/main.min.js'></script>
<script src='lib/fullcalendar/interaction/main.min.js'></script>
<script src='lib/fullcalendar/list/main.min.js'></script>
<script src='lib/fullcalendar/timegrid/main.min.js'></script>
<script src="js/calendar.js"></script>
<script src="lib/datatables/js/query-3.5.1.js"></script>

<!-- Exibição dos campos RG e CPF de acordo com o documento escolhido -->
<script>
    $('#input-rg-cadastro').hide();
    $('#label-uf-cadastro').hide();
    $('#select-uf-cadastro').hide();

    $("#select-documento-cadastro").change(function() {
        if (this.value == "RG") {
            $('#input-rg-cadastro').show();
            $('#label-uf-cadastro').show();
            $('#select-uf-cadastro').show();
            $('#input-cpf-cadastro').hide()
        } else if (this.value == "CPF") {
            $('#input-rg-cadastro').hide();
            $('#label-uf-cadastro').hide();
            $('#select-uf-cadastro').hide();
            $('#input-cpf-cadastro').show();
        }
    });

    $('#input-rg-registro').hide();
    $('#label-uf-registro').hide();
    $('#select-uf-registro').hide();
    //$('#label-placa_veiculo').hide();
    

    $("#select-documento-registro").change(function() {
        if (this.value == "RG") {
            $('#input-rg-registro').show();
            $('#label-uf-registro').show();
            $('#select-uf-registro').show();
            $('#input-cpf-registro').hide()
        } else if (this.value == "CPF") {
            $('#input-rg-registro').hide();
            $('#label-uf-registro').hide();
            $('#select-uf-registro').hide();
            $('#input-cpf-registro').show();
        }
    });

    // Exportação de dados
    $('#label-periodo-export').hide();
    $('#select-periodo-export').hide();
    $('#label-data-inicio').hide();
    $('#input-data-inicio').hide();
    $('#label-data-fim').hide();
    $('#input-data-fim').hide();

    $("#select-documento-export").change(function() {
        if (this.value == "Cadastros") {
            $('#label-periodo-export').hide();
            $('#select-periodo-export').hide();
            $('#label-data-inicio').hide();
            $('#input-data-inicio').hide();
            $('#label-data-fim').hide();
            $('#input-data-fim').hide();
        } else if (this.value == "Registros") {
            $('#label-periodo-export').show();
            $('#select-periodo-export').show();
            $('#label-data-inicio').hide();
            $('#input-data-inicio').hide();
            $('#label-data-fim').hide();
            $('#input-data-fim').hide();
        }
    });

    $("#select-periodo-export").change(function() {
        if (this.value == "Todo o período") {
            $('#label-data-inicio').hide();
            $('#input-data-inicio').hide();
            $('#label-data-fim').hide();
            $('#input-data-fim').hide();
        } else if (this.value == "Personalizado") {
            $('#label-data-inicio').show();
            $('#input-data-inicio').show();
            $('#label-data-fim').show();
            $('#input-data-fim').show();
        }
    });

    
    function validarDsc(entradaDoUsuario) {
        
        var veiculo = entradaDoUsuario.value; // Passa para a variável 'placa' o que o usuário digitar no formulário
        
        veiculoMaiuscula = veiculo.toUpperCase();                      // Passa a string para letras maiúsculas
        //document.forms[0].placa.value = placaMaiuscula;    // Coloca a string modificada de volta no formulário
        document.getElementById('dsc_veiculo').value = veiculoMaiuscula;
        return true;
}
    
    function validarPlaca(entradaDoUsuario) {
        
        var placa = entradaDoUsuario.value; // Passa para a variável 'placa' o que o usuário digitar no formulário
        
        if (placa.length === 1 || placa.length === 2 || placa.length > 3) {                       // Quando a string possuir 1 ou 2 dígitos
                placaMaiuscula = placa.toUpperCase();                      // Passa a string para letras maiúsculas
                //document.forms[0].placa.value = placaMaiuscula;    // Coloca a string modificada de volta no formulário
                document.getElementById('placa_veiculo').value = placaMaiuscula;
                return true;
        }
 
        if (placa.length === 3){                                                        // Quando a string possuir 3 dígitos
                placa += "-";                                                                 // Adiciona um hífen
                placaMaiuscula = placa.toUpperCase();                   // Passa a string para letras maiúsculas
                //document.forms[0].placa.value = placaMaiuscula; // Coloca a nova string de volta no formulário
                document.getElementById('placa_veiculo').value = placaMaiuscula;
                return true;
    }
}


</script>