<html lang="pt-BR">

<head>
	<title>Cannes</title>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<meta name="author" content="Rafael Tavares" />

	<link rel="stylesheet" href="https://www.cannesresidence.com.br/public/lib/bootstrap/css/bootstrap.min.css" />
	<link rel="stylesheet" href="https://www.cannesresidence.com.br/public/lib/fontawesome/css/all.min.css">
	<link rel="stylesheet" href="https://www.cannesresidence.com.br/public/lib/datatables/css/query.datatable.min.css" />
	<link rel="stylesheet" href="https://www.cannesresidence.com.br/public/lib/datatables/css/responsive.datatable.min.css" />
	<link rel="stylesheet" href="https://www.cannesresidence.com.br/public/lib/datatables/css/dataTables.bootstrap4.min.css" />
	<link rel="stylesheet" href='https://www.cannesresidence.com.br/public/lib/fullcalendar/core/main.min.css' />
	<link rel="stylesheet" href='https://www.cannesresidence.com.br/public/lib/fullcalendar/daygrid/main.min.css' />
	<link rel="stylesheet" href='https://www.cannesresidence.com.br/public/lib/fullcalendar/timegrid/main.min.css' />
	<link rel="stylesheet" href='https://www.cannesresidence.com.br/public/lib/fullcalendar/list/main.min.css' />
	<link rel="shortcut icon" href="https://www.cannesresidence.com.br/public/favicon.ico">

	<link rel="stylesheet" href="https://www.cannesresidence.com.br/public/css/all.css" />
	<link rel="stylesheet" href="https://www.cannesresidence.com.br/public/css/content.css" />
	<link rel="stylesheet" href="https://www.cannesresidence.com.br/public/css/header.css" />
	<link rel="stylesheet" href="https://www.cannesresidence.com.br/public/css/dashboard.css" />
	<link rel="stylesheet" href="https://www.cannesresidence.com.br/public/css/calendar.css" />
	<link rel="stylesheet" href="https://www.cannesresidence.com.br/public/css/login-register.css" />
	<link rel="stylesheet" href="https://www.cannesresidence.com.br/public/css/user_profile.css" />
	<script src="https://www.cannesresidence.com.br/public/js/not-supported.js"></script>
</head>

<body onload="identifyBrowser();">
	<?= $this->content() ?>

	<script src="https://www.cannesresidence.com.br/public/lib/datatables/js/popper.js"></script>
	<script src="https://www.cannesresidence.com.br/public/lib/datatables/js/query-3.5.1.js"></script>
	<script src="https://www.cannesresidence.com.br/public/lib/datatables/js/jquery.dataTables.min.js"></script>
	<script src="https://www.cannesresidence.com.br/public/lib/datatables/js/datatable.responsive.js"></script>
	<script src="https://www.cannesresidence.com.br/public/lib/datatables/js/dataTables.bootstrap4.min.js"></script>
	<script src="https://www.cannesresidence.com.br/public/lib/datatables/js/datatable.js"></script>
	<script src="https://www.cannesresidence.com.br/public/lib/bootstrap/js/bootstrap.min.js"></script>
	<script src="https://www.cannesresidence.com.br/public/lib/jquery/jquery.mask.min.js"></script>

	
	<script src="https://www.cannesresidence.com.br/public/js/mask-rg.js"></script>
	<script src="https://www.cannesresidence.com.br/public/js/validation.js"></script>
	<script src="https://www.cannesresidence.com.br/public/js/menu-user.js"></script>

	<script>
		$("#cpf").mask("999.999.999-99");
		$("#cad-cpf").mask("999.999.999-99");
		$("#rg").mask("99.999.999-9");
		$("#cad-rg").mask("99.999.999-9");
		$("#telefone").mask("(99) 9999-99999");
		$("#data_nascimento").mask("99/99/9999");
	</script>
</body>

</html>